### ISSUE TITLE
Route doesn't allow an array callable (eg.: [$obj, 'method'])

### ISSUE THREAD

**Issue by G4MR** [thephpleague/route#61]
Simple example of this not working:

    $test = new Test();
    $router = new League\Route\RouteCollection;
    $router->addRoute('GET', '/', [$test, 'index']);

    $request    = Request::createFromGlobals();
    $dispatcher = $router->getDispatcher();

    try {
        $response   = $dispatcher->dispatch($request->getMethod(), $request->getPathInfo());
        $response->send();
    } catch(Exception $e) {
        echo $e->getMessage();
    }

    class Test
    {
        public function index(Request $req, Response $resp) 
        {
            $resp->setContent("Testing");
            return $resp;
        }
    }

Errors:

    Warning: Illegal offset type in /var/www/source/vendor/league/route/src/RouteCollection.php on line 84

    Warning: Illegal offset type in /var/www/source/vendor/league/route/src/RouteCollection.php on line 84

    Warning: Illegal offset type in /var/www/source/vendor/league/route/src/Dispatcher.php on line 69

    Warning: Illegal offset type in /var/www/source/vendor/league/route/src/Dispatcher.php on line 70

    Catchable fatal error: Argument 2 passed to League\Route\Dispatcher::handleFound() must implement interface League\Route\Strategy\StrategyInterface, null given, called in /var/www/source/vendor/league/route/src/Dispatcher.php on line 73 and defined in /var/www/source/vendor/league/route/src/Dispatcher.php on line 85

Doing the following works as expected though:

    $router->addRoute('GET', '/', 'test::index');

Both ways are valid callables, so this not working is weird.

**Comment by G4MR** [comment]
Trying to debug this myself locally, in RouteCollection on line 72 I change:

    if ($handler instanceof Closure ||
        (is_object($handler) && is_callable($handler))
    ) {

to 

    if ($handler instanceof Closure ||
        (is_object($handler) || is_callable($handler))
    ) {

Fixes the first error, then you get a new set of errors which I didn't get that far with:

    Warning: array_key_exists(): The first argument should be either a string or an integer in /var/www/source/vendor/league/container/src/Container.php on line 189

    Warning: array_key_exists(): The first argument should be either a string or an integer in /var/www/source/vendor/league/container/src/Container.php on line 194

    Warning: Illegal offset type in /var/www/source/vendor/league/container/src/Container.php on line 208

    Fatal error: Function name must be a string in /var/www/source/vendor/league/container/src/Container.php on line 210

**Comment by philipobenito** [comment]
Will have a look at this tomorrow morning and ensure all callables are
accepted

**Comment by G4MR** [comment]
I figured out what's wrong or a solution to my issue:

RouteCollection on line 72 I change:

    if ($handler instanceof Closure ||
        (is_object($handler) && is_callable($handler))
    ) {

to 

    if ($handler instanceof Closure ||
        (is_object($handler) || is_callable($handler))
    ) {

And in Strategy/AbstractStrategy.php on line 27 if I changed line 27 from:

                $this->getContainer()->get($controller[0]),

to 

                $controller[0],

Everything works as expected.  Both [$test, 'index'] and 'test::index', now I'm assuming this line creates a new object for the controller and then attempts to call it normally so you don't have to forcefully call static on the class method.  I guess a simple solution would be to check if $controller[0] is already an object?

    $controller = [
        is_object($controller[0]) ? $controller[0] : $this->getContainer()->get($controller[0]),
        $controller[1]
    ];

**Comment by philipobenito** [comment]
It's not actually a static call but a pointer so that the class can be
resolved via the container, your solution looks to be correct but I need to
be sure it fits all scenarios so I'll put together some test cases tomorrow
and get all of them passing.

**Comment by G4MR** [comment]
Sounds good.

**Comment by philipobenito** [comment]
Should be fixed by 6029f146900f76c4dfa53632cdf71615fd720704

**Comment by G4MR** [comment]
Did you forget to update AbstractStrategy.php on [Line 27](https://github.com/thephpleague/route/blob/master/src/Strategy/AbstractStrategy.php#L27) because I'm still getting:

    Warning: array_key_exists(): The first argument should be either a string or an integer in /var/www/source/vendor/league/container/src/Container.php on line 189

    Warning: array_key_exists(): The first argument should be either a string or an integer in /var/www/source/vendor/league/container/src/Container.php on line 194

    Warning: Illegal offset type in /var/www/source/vendor/league/container/src/Container.php on line 208

    Fatal error: Function name must be a string in /var/www/source/vendor/league/container/src/Container.php on line 210

I played with my solution above checking $controller[0] to see if it was an object already seemed to work locally.

**Comment by philipobenito** [comment]
Yep, apologies, I rushed that, will add the check asap

**Comment by G4MR** [comment]
alright

**Comment by G4MR** [comment]
I noticed you've written another version under the develop branch, when is that expected to drop because it has some features that I've wanted like get,post,etc... to shorten the length of the addRoute method (now map in develop)

**Comment by philipobenito** [comment]
@G4MR expect a tag over the weekend, however, those convenience methods are already there in version 1

**Comment by G4MR** [comment]
> those convenience methods are already there in version 1

I must have overlooked them.

**Comment by philipobenito** [comment]
tag/1.2.3

**Comment by G4MR** [comment]
thanks :)

**Comment by ericktucto** [comment]
Hello, I use the magic method __invoke to use the instance of the class to group routes
```php
<?php
use League\Route\RouteGroup;

abstract class Router
{
  abstract protected function routes(RouteGroup $group);
  public function __invoke(RouteGroup $group)
  {
    $this->routes($group);
  }
}

class UserRoutes extends Router
{
  protected function routes(RouteGroup $group)
  {
    $group->post("/users", "UserController::index");
  }
}
$router  = new League\Route\Router;
$request = new Request; // Psr\Http\Message\ServerRequestInterface

// Using UserRoutes
$router->group("/api", new UserRoutes());

$response = $router->dispatch($request);
```
